In [2]:
import numpy as np

def generate_batches(X, y, batch_size):
    """
    param X: np.array[n_objects, n_features]
    param y: np.array[n_objects]
    """
    assert len(X) == len(y)
    np.random.seed(42)
    X = np.array(X)
    y = np.array(y)
    perm = np.random.permutation(len(X))
    ind = []
    start = 0
    end = batch_size

    for batch_start in range(len(X)//batch_size):
      ind = perm[start:end]
      yield (X[np.array(ind)], y[np.array(ind)])
      ind = []
      start += batch_size
      end += batch_size

In [3]:
X_fake = np.arange(100)[:, np.newaxis]
y_fake = np.arange(100) + 1000

In [5]:
k = 0
for batch_X, batch_y in generate_batches(X_fake, y_fake, 9):
  print("Batch №", k, "\n", batch_X,batch_y, "\n\n")
  k += 1

Batch № 0 
 [[83]
 [53]
 [70]
 [45]
 [44]
 [39]
 [22]
 [80]
 [10]] [1083 1053 1070 1045 1044 1039 1022 1080 1010] 


Batch № 1 
 [[ 0]
 [18]
 [30]
 [73]
 [33]
 [90]
 [ 4]
 [76]
 [77]] [1000 1018 1030 1073 1033 1090 1004 1076 1077] 


Batch № 2 
 [[12]
 [31]
 [55]
 [88]
 [26]
 [42]
 [69]
 [15]
 [40]] [1012 1031 1055 1088 1026 1042 1069 1015 1040] 


Batch № 3 
 [[96]
 [ 9]
 [72]
 [11]
 [47]
 [85]
 [28]
 [93]
 [ 5]] [1096 1009 1072 1011 1047 1085 1028 1093 1005] 


Batch № 4 
 [[66]
 [65]
 [35]
 [16]
 [49]
 [34]
 [ 7]
 [95]
 [27]] [1066 1065 1035 1016 1049 1034 1007 1095 1027] 


Batch № 5 
 [[19]
 [81]
 [25]
 [62]
 [13]
 [24]
 [ 3]
 [17]
 [38]] [1019 1081 1025 1062 1013 1024 1003 1017 1038] 


Batch № 6 
 [[ 8]
 [78]
 [ 6]
 [64]
 [36]
 [89]
 [56]
 [99]
 [54]] [1008 1078 1006 1064 1036 1089 1056 1099 1054] 


Batch № 7 
 [[43]
 [50]
 [67]
 [46]
 [68]
 [61]
 [97]
 [79]
 [41]] [1043 1050 1067 1046 1068 1061 1097 1079 1041] 


Batch № 8 
 [[58]
 [48]
 [98]
 [57]
 [75]
 [32]
 [94]
 [59]
 [63